create table admins (
    id bigint generated by default as identity,
    authority varchar(15) not null,
    firstname varchar(128),
    lastname varchar(128),
    password varchar(128),
    phone_number varchar(15),
    username varchar(128),
    iin varchar(12),
    primary key (id)
);

create table categories (
    id bigint generated by default as identity,
    name varchar(74),
    primary key (id)
);

create table coach_trainee (
    coach_id bigint not null,
    trainee_id bigint not null,
    primary key (coach_id, trainee_id)
);

create table coaches (
    id bigint generated by default as identity,
    authority varchar(15) not null,
    firstname varchar(128),
    lastname varchar(128),
    password varchar(128),
    phone_number varchar(15),
    username varchar(128),
    achievements varchar(512),
    category varchar(255),
    sport_class varchar(128),
    primary key (id)
);

create table comments (
    id bigint generated by default as identity,
    comment_business_key varchar(255),
    text varchar(120),
    post_id bigint,
    trainee_id bigint,
    primary key (id)
);

create table posts (
    id bigint generated by default as identity,
    post_business_key varchar(255),
    text varchar(2048),
    topic varchar(50),
    category_id bigint,
    coach_id bigint,
    primary key (id)
);

create table trainees (
    id bigint generated by default as identity,
    authority varchar(15) not null,
    firstname varchar(128),
    lastname varchar(128),
    password varchar(128),
    phone_number varchar(15),
    username varchar(128),
    height integer,
    purpose varchar(255),
    weight integer,
    primary key (id)
);

alter table admins
    add constraint UK_mi8vkhus4xbdbqcac2jm4spvd unique (username);

alter table admins
    add constraint UK_em0mk5euq90ei084poc1xfq1g unique (iin);

alter table categories
    add constraint UK_t8o6pivur7nn124jehx7cygw5 unique (name);

alter table coaches
    add constraint UK_j976g6mml6do2us2cao9n0k8l unique (username);

alter table comments
    add constraint UK_c06gb471n0vx44hcxu3c1dw07 unique (comment_business_key);

alter table posts
    add constraint UK_mw656kjdbk4ln36i5xaj59yu4 unique (post_business_key);

alter table trainees
    add constraint UK_1wqkgvgcd4ai4n1dilk2wkl51 unique (username);

alter table coach_trainee
    add constraint trainee_coach_fk
        foreign key (trainee_id)
            references trainees;

alter table coach_trainee
    add constraint coach_trainee_fk
        foreign key (coach_id)
            references coaches;

alter table comments
    add constraint FKh4c7lvsc298whoyd4w9ta25cr
        foreign key (post_id)
            references posts;

alter table comments
    add constraint FKip04byp5usbh4gdyn6nvlmbax
        foreign key (trainee_id)
            references trainees;

alter table posts
    add constraint FKqysujf9oy72eniir74cq93s2d
        foreign key (category_id)
            references categories;

alter table posts
    add constraint FKp9vsdqhurr6len51am80k4i9h
        foreign key (coach_id)
            references coaches;